### ISSUE TITLE
Sessions API

### ISSUE THREAD

**Issue by rgbkrk** [nteract/rx-jupyter#12]
Similar to how we've done `kernels` and `kernelspecs`, implement the sessions API.

**References**

* [IPython URL "map"](https://github.com/ipython/ipython/wiki/Dev:-URL-mapping-of-IPython-notebook#sessions-api)
* [Jupyter API for sessions](http://jupyter-api.surge.sh/#/sessions)

**rx-jupyter API**

* [x] `jupyter.sessions.list(server)`

List available sessions

```
GET /sessions
```

* [x] `jupyter.sessions.get(server, sessionID)`

Get session

```
GET /sessions/{session}
```

* [x] `jupyter.sessions.delete(server, sessionID)`

Delete a session

```
DELETE /sessions/{session}
```

* [x] `jupyter.sessions.update(server, sessionID, ???)` (`reconfigure`?)

This can be used to rename the session. [sic] (_Ed: can you change the kernel with this?_)

```
PATCH /sessions/{session}
```

* [x] `jupyter.sessions.create(server, name, path, type, kernel)`

Create a new session, or return an existing session if a session of the same name already exists. This function uses the `path`, `type`, and `kernel` parameters to create a new `kernel` for the session at the `path` provided. 

```
POST /sessions
```

**Comment by jdetle** [comment]
I have started work on this! Appreciate the background info.

**Comment by jdetle** [comment]
Was the `sessionID` parameter in `sessions.list` intentional?

**Comment by jdetle** [comment]
seems like it should be `jupyter.sessions.create(server, notebookName, path, kernelName)`

**Comment by rgbkrk** [comment]
> Was the sessionID parameter in sessions.list intentional?

Oops! Nope.

**Comment by rgbkrk** [comment]
> Also, create seems like it should be jupyter.sessions.create(server, notebookName, path, kernelName). Thanks for any input.

I'd probably make that an object

```
jupyter.sessions.create(server, { notebookName, path, kernelName })
```

Though if there are only ever going to be a few args, it's fine to do args. The reason I suggest an object is that's it's our only option for keyword args and allows us flexibility to manage more arguments in the payload to the `POST`.

**Comment by rgbkrk** [comment]
I've got a demo "site" that runs with the jupyter notebook in case you want to use that while trying out this API. You can also `curl -X POST` or use `requests` against a running notebook server to check out the notebook API.

**Comment by rgbkrk** [comment]
Done in #13.
