### ISSUE TITLE
Terminal API

### ISSUE THREAD

**Issue by rgbkrk** [nteract/rx-jupyter#27]
* [x] Rest API
  * [x] list `GET /api/terminals`
  * [x] create `POST /api/terminals`
  * [x] get `GET /api/terminals/${name}`
  * [x] kill `DELETE /api/terminals/${name}`
* [x] Websocket API
  * [x] `ws://${basePath}/terminals/websocket/${name}`
  * ⚠️ Note that this is not on the api path, unlike the kernel channels/websockets which are subresources of the REST API
* [x] Update the [jupyter notebook swagger doc](https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml)

**Comment by jdetle** [comment]
@rgbkrk, is this issue closed?

**Comment by rgbkrk** [comment]
Totally.
